# permissions for end users to edit lenshoodraftclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lenshoodraftcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-raft-operator
    app.kubernetes.io/part-of: go-raft-operator
    app.kubernetes.io/managed-by: kustomize
  name: lenshoodraftcluster-editor-role
rules:
- apiGroups:
  - lenshood.github.io
  resources:
  - lenshoodraftclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lenshood.github.io
  resources:
  - lenshoodraftclusters/status
  verbs:
  - get
