apiVersion: lenshood.github.io/v1
kind: LenshoodRaftCluster
metadata:
  labels:
    app.kubernetes.io/name: lenshoodraftcluster
    app.kubernetes.io/instance: lenshoodraftcluster-sample
    app.kubernetes.io/part-of: go-raft-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: go-raft-operator
  name: lenshoodraftcluster-sample
spec:
  replica: 3
  image: registry.cn-hangzhou.aliyuncs.com/lenshood/go-raft:v0.1.0
